package com.marcosperboni.order.domain;

public enum OrderStatus {
	PENDING,
	PAYMENT_PENDING,
	PAYMENT_REJECTED,
	PAYMENT_APPROVED,
	INVENTORY_PENDING,
	INVENTORY_REJECTED,
	COMPENSATING_PAYMENT,
	CONFIRMED,
	CANCELLED
}
